################################################################################
# 自动生成的文件。不要编辑！
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/src/clock.c \
C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/src/components.c \
C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/src/device.c \
C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/src/idle.c \
C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/src/ipc.c \
C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/src/irq.c \
C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/src/kservice.c \
C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/src/mem.c \
C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/src/memheap.c \
C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/src/mempool.c \
C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/src/object.c \
C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/src/scheduler.c \
C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/src/signal.c \
C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/src/thread.c \
C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/src/timer.c 

OBJS += \
./Kernel/clock.o \
./Kernel/components.o \
./Kernel/device.o \
./Kernel/idle.o \
./Kernel/ipc.o \
./Kernel/irq.o \
./Kernel/kservice.o \
./Kernel/mem.o \
./Kernel/memheap.o \
./Kernel/mempool.o \
./Kernel/object.o \
./Kernel/scheduler.o \
./Kernel/signal.o \
./Kernel/thread.o \
./Kernel/timer.o 

C_DEPS += \
./Kernel/clock.d \
./Kernel/components.d \
./Kernel/device.d \
./Kernel/idle.d \
./Kernel/ipc.d \
./Kernel/irq.d \
./Kernel/kservice.d \
./Kernel/mem.d \
./Kernel/memheap.d \
./Kernel/mempool.d \
./Kernel/object.d \
./Kernel/scheduler.d \
./Kernel/signal.d \
./Kernel/thread.d \
./Kernel/timer.d 


# Each subdirectory must supply rules for building sources it contributes
Kernel/clock.o: C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/src/clock.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -D RT_USING_ARM_LIBC -D STM32F103xE -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/applications -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/drivers -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Device/ST/STM32F1xx/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/STM32F1xx_HAL_Driver/Inc -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/basic/led -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/kernel/thread -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/cortex-m3 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/common -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/finsh -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/libc/compilers/armlibc -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
Kernel/components.o: C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/src/components.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -D RT_USING_ARM_LIBC -D STM32F103xE -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/applications -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/drivers -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Device/ST/STM32F1xx/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/STM32F1xx_HAL_Driver/Inc -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/basic/led -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/kernel/thread -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/cortex-m3 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/common -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/finsh -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/libc/compilers/armlibc -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
Kernel/device.o: C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/src/device.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -D RT_USING_ARM_LIBC -D STM32F103xE -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/applications -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/drivers -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Device/ST/STM32F1xx/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/STM32F1xx_HAL_Driver/Inc -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/basic/led -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/kernel/thread -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/cortex-m3 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/common -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/finsh -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/libc/compilers/armlibc -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
Kernel/idle.o: C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/src/idle.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -D RT_USING_ARM_LIBC -D STM32F103xE -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/applications -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/drivers -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Device/ST/STM32F1xx/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/STM32F1xx_HAL_Driver/Inc -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/basic/led -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/kernel/thread -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/cortex-m3 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/common -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/finsh -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/libc/compilers/armlibc -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
Kernel/ipc.o: C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/src/ipc.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -D RT_USING_ARM_LIBC -D STM32F103xE -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/applications -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/drivers -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Device/ST/STM32F1xx/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/STM32F1xx_HAL_Driver/Inc -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/basic/led -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/kernel/thread -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/cortex-m3 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/common -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/finsh -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/libc/compilers/armlibc -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
Kernel/irq.o: C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/src/irq.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -D RT_USING_ARM_LIBC -D STM32F103xE -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/applications -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/drivers -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Device/ST/STM32F1xx/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/STM32F1xx_HAL_Driver/Inc -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/basic/led -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/kernel/thread -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/cortex-m3 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/common -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/finsh -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/libc/compilers/armlibc -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
Kernel/kservice.o: C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/src/kservice.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -D RT_USING_ARM_LIBC -D STM32F103xE -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/applications -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/drivers -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Device/ST/STM32F1xx/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/STM32F1xx_HAL_Driver/Inc -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/basic/led -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/kernel/thread -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/cortex-m3 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/common -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/finsh -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/libc/compilers/armlibc -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
Kernel/mem.o: C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/src/mem.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -D RT_USING_ARM_LIBC -D STM32F103xE -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/applications -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/drivers -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Device/ST/STM32F1xx/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/STM32F1xx_HAL_Driver/Inc -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/basic/led -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/kernel/thread -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/cortex-m3 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/common -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/finsh -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/libc/compilers/armlibc -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
Kernel/memheap.o: C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/src/memheap.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -D RT_USING_ARM_LIBC -D STM32F103xE -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/applications -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/drivers -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Device/ST/STM32F1xx/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/STM32F1xx_HAL_Driver/Inc -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/basic/led -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/kernel/thread -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/cortex-m3 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/common -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/finsh -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/libc/compilers/armlibc -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
Kernel/mempool.o: C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/src/mempool.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -D RT_USING_ARM_LIBC -D STM32F103xE -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/applications -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/drivers -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Device/ST/STM32F1xx/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/STM32F1xx_HAL_Driver/Inc -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/basic/led -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/kernel/thread -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/cortex-m3 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/common -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/finsh -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/libc/compilers/armlibc -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
Kernel/object.o: C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/src/object.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -D RT_USING_ARM_LIBC -D STM32F103xE -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/applications -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/drivers -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Device/ST/STM32F1xx/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/STM32F1xx_HAL_Driver/Inc -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/basic/led -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/kernel/thread -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/cortex-m3 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/common -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/finsh -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/libc/compilers/armlibc -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
Kernel/scheduler.o: C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/src/scheduler.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -D RT_USING_ARM_LIBC -D STM32F103xE -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/applications -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/drivers -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Device/ST/STM32F1xx/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/STM32F1xx_HAL_Driver/Inc -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/basic/led -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/kernel/thread -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/cortex-m3 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/common -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/finsh -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/libc/compilers/armlibc -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
Kernel/signal.o: C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/src/signal.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -D RT_USING_ARM_LIBC -D STM32F103xE -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/applications -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/drivers -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Device/ST/STM32F1xx/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/STM32F1xx_HAL_Driver/Inc -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/basic/led -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/kernel/thread -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/cortex-m3 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/common -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/finsh -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/libc/compilers/armlibc -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
Kernel/thread.o: C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/src/thread.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -D RT_USING_ARM_LIBC -D STM32F103xE -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/applications -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/drivers -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Device/ST/STM32F1xx/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/STM32F1xx_HAL_Driver/Inc -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/basic/led -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/kernel/thread -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/cortex-m3 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/common -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/finsh -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/libc/compilers/armlibc -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
Kernel/timer.o: C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/src/timer.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -D RT_USING_ARM_LIBC -D STM32F103xE -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/applications -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/drivers -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Device/ST/STM32F1xx/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/STM32F1xx_HAL_Driver/Inc -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/basic/led -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/kernel/thread -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/cortex-m3 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/common -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/finsh -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/libc/compilers/armlibc -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"

