################################################################################
# 自动生成的文件。不要编辑！
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/kernel-sample-0.1.0/dynmem_sample.c \
C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/kernel-sample-0.1.0/event_sample.c \
C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/kernel-sample-0.1.0/idlehook_sample.c \
C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/kernel-sample-0.1.0/interrupt_sample.c \
C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/kernel-sample-0.1.0/mailbox_sample.c \
C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/kernel-sample-0.1.0/memp_sample.c \
C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/kernel-sample-0.1.0/msgq_sample.c \
C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/kernel-sample-0.1.0/mutex_sample.c \
C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/kernel-sample-0.1.0/priority_inversion.c \
C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/kernel-sample-0.1.0/producer_consumer.c \
C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/kernel-sample-0.1.0/scheduler_hook.c \
C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/kernel-sample-0.1.0/semaphore_sample.c \
C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/kernel-sample-0.1.0/signal_sample.c \
C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/kernel-sample-0.1.0/thread_sample.c \
C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/kernel-sample-0.1.0/timer_sample.c \
C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/kernel-sample-0.1.0/timeslice_sample.c 

OBJS += \
./kernel-sample/dynmem_sample.o \
./kernel-sample/event_sample.o \
./kernel-sample/idlehook_sample.o \
./kernel-sample/interrupt_sample.o \
./kernel-sample/mailbox_sample.o \
./kernel-sample/memp_sample.o \
./kernel-sample/msgq_sample.o \
./kernel-sample/mutex_sample.o \
./kernel-sample/priority_inversion.o \
./kernel-sample/producer_consumer.o \
./kernel-sample/scheduler_hook.o \
./kernel-sample/semaphore_sample.o \
./kernel-sample/signal_sample.o \
./kernel-sample/thread_sample.o \
./kernel-sample/timer_sample.o \
./kernel-sample/timeslice_sample.o 

C_DEPS += \
./kernel-sample/dynmem_sample.d \
./kernel-sample/event_sample.d \
./kernel-sample/idlehook_sample.d \
./kernel-sample/interrupt_sample.d \
./kernel-sample/mailbox_sample.d \
./kernel-sample/memp_sample.d \
./kernel-sample/msgq_sample.d \
./kernel-sample/mutex_sample.d \
./kernel-sample/priority_inversion.d \
./kernel-sample/producer_consumer.d \
./kernel-sample/scheduler_hook.d \
./kernel-sample/semaphore_sample.d \
./kernel-sample/signal_sample.d \
./kernel-sample/thread_sample.d \
./kernel-sample/timer_sample.d \
./kernel-sample/timeslice_sample.d 


# Each subdirectory must supply rules for building sources it contributes
kernel-sample/dynmem_sample.o: C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/kernel-sample-0.1.0/dynmem_sample.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -D RT_USING_ARM_LIBC -D STM32F103xE -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/applications -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/drivers -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Device/ST/STM32F1xx/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/STM32F1xx_HAL_Driver/Inc -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/basic/led -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/kernel/thread -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/cortex-m3 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/common -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/finsh -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/libc/compilers/armlibc -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
kernel-sample/event_sample.o: C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/kernel-sample-0.1.0/event_sample.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -D RT_USING_ARM_LIBC -D STM32F103xE -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/applications -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/drivers -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Device/ST/STM32F1xx/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/STM32F1xx_HAL_Driver/Inc -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/basic/led -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/kernel/thread -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/cortex-m3 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/common -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/finsh -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/libc/compilers/armlibc -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
kernel-sample/idlehook_sample.o: C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/kernel-sample-0.1.0/idlehook_sample.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -D RT_USING_ARM_LIBC -D STM32F103xE -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/applications -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/drivers -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Device/ST/STM32F1xx/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/STM32F1xx_HAL_Driver/Inc -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/basic/led -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/kernel/thread -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/cortex-m3 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/common -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/finsh -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/libc/compilers/armlibc -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
kernel-sample/interrupt_sample.o: C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/kernel-sample-0.1.0/interrupt_sample.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -D RT_USING_ARM_LIBC -D STM32F103xE -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/applications -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/drivers -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Device/ST/STM32F1xx/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/STM32F1xx_HAL_Driver/Inc -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/basic/led -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/kernel/thread -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/cortex-m3 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/common -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/finsh -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/libc/compilers/armlibc -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
kernel-sample/mailbox_sample.o: C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/kernel-sample-0.1.0/mailbox_sample.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -D RT_USING_ARM_LIBC -D STM32F103xE -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/applications -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/drivers -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Device/ST/STM32F1xx/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/STM32F1xx_HAL_Driver/Inc -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/basic/led -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/kernel/thread -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/cortex-m3 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/common -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/finsh -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/libc/compilers/armlibc -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
kernel-sample/memp_sample.o: C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/kernel-sample-0.1.0/memp_sample.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -D RT_USING_ARM_LIBC -D STM32F103xE -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/applications -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/drivers -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Device/ST/STM32F1xx/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/STM32F1xx_HAL_Driver/Inc -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/basic/led -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/kernel/thread -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/cortex-m3 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/common -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/finsh -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/libc/compilers/armlibc -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
kernel-sample/msgq_sample.o: C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/kernel-sample-0.1.0/msgq_sample.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -D RT_USING_ARM_LIBC -D STM32F103xE -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/applications -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/drivers -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Device/ST/STM32F1xx/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/STM32F1xx_HAL_Driver/Inc -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/basic/led -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/kernel/thread -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/cortex-m3 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/common -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/finsh -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/libc/compilers/armlibc -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
kernel-sample/mutex_sample.o: C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/kernel-sample-0.1.0/mutex_sample.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -D RT_USING_ARM_LIBC -D STM32F103xE -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/applications -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/drivers -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Device/ST/STM32F1xx/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/STM32F1xx_HAL_Driver/Inc -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/basic/led -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/kernel/thread -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/cortex-m3 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/common -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/finsh -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/libc/compilers/armlibc -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
kernel-sample/priority_inversion.o: C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/kernel-sample-0.1.0/priority_inversion.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -D RT_USING_ARM_LIBC -D STM32F103xE -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/applications -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/drivers -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Device/ST/STM32F1xx/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/STM32F1xx_HAL_Driver/Inc -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/basic/led -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/kernel/thread -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/cortex-m3 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/common -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/finsh -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/libc/compilers/armlibc -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
kernel-sample/producer_consumer.o: C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/kernel-sample-0.1.0/producer_consumer.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -D RT_USING_ARM_LIBC -D STM32F103xE -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/applications -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/drivers -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Device/ST/STM32F1xx/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/STM32F1xx_HAL_Driver/Inc -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/basic/led -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/kernel/thread -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/cortex-m3 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/common -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/finsh -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/libc/compilers/armlibc -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
kernel-sample/scheduler_hook.o: C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/kernel-sample-0.1.0/scheduler_hook.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -D RT_USING_ARM_LIBC -D STM32F103xE -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/applications -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/drivers -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Device/ST/STM32F1xx/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/STM32F1xx_HAL_Driver/Inc -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/basic/led -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/kernel/thread -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/cortex-m3 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/common -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/finsh -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/libc/compilers/armlibc -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
kernel-sample/semaphore_sample.o: C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/kernel-sample-0.1.0/semaphore_sample.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -D RT_USING_ARM_LIBC -D STM32F103xE -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/applications -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/drivers -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Device/ST/STM32F1xx/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/STM32F1xx_HAL_Driver/Inc -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/basic/led -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/kernel/thread -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/cortex-m3 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/common -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/finsh -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/libc/compilers/armlibc -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
kernel-sample/signal_sample.o: C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/kernel-sample-0.1.0/signal_sample.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -D RT_USING_ARM_LIBC -D STM32F103xE -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/applications -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/drivers -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Device/ST/STM32F1xx/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/STM32F1xx_HAL_Driver/Inc -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/basic/led -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/kernel/thread -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/cortex-m3 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/common -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/finsh -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/libc/compilers/armlibc -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
kernel-sample/thread_sample.o: C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/kernel-sample-0.1.0/thread_sample.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -D RT_USING_ARM_LIBC -D STM32F103xE -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/applications -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/drivers -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Device/ST/STM32F1xx/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/STM32F1xx_HAL_Driver/Inc -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/basic/led -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/kernel/thread -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/cortex-m3 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/common -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/finsh -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/libc/compilers/armlibc -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
kernel-sample/timer_sample.o: C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/kernel-sample-0.1.0/timer_sample.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -D RT_USING_ARM_LIBC -D STM32F103xE -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/applications -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/drivers -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Device/ST/STM32F1xx/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/STM32F1xx_HAL_Driver/Inc -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/basic/led -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/kernel/thread -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/cortex-m3 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/common -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/finsh -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/libc/compilers/armlibc -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
kernel-sample/timeslice_sample.o: C:/Users/86135/Desktop/rtthread_simulator_v0.1.0/kernel-sample-0.1.0/timeslice_sample.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -D RT_USING_ARM_LIBC -D STM32F103xE -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/applications -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/drivers -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Device/ST/STM32F1xx/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/STM32F1xx_HAL_Driver/Inc -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/Libraries/CMSIS/Include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/basic/led -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/packages/samples/kernel/thread -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/cortex-m3 -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/libcpu/arm/common -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/drivers/include -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/finsh -IC:/Users/86135/Desktop/rtthread_simulator_v0.1.0/rt-thread/components/libc/compilers/armlibc -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"

